### ISSUE TITLE
Forked CI pipelines fail due to Firebase Config not available

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo_api#682] opened 2023-06-21 14:12 UTC
**Describe the bug**
When a contributor attempts to run their changes against the main repo's CI pipeline, it always fails because of the following error:

[`error: option '--token <token>' argument missing`](https://github.com/nkowaokwu/igbo_api/actions/runs/5330258088/jobs/9667631425?pr=677)

![image](https://github.com/nkowaokwu/igbo_api/assets/16169291/6dc81acb-e963-4b57-978e-7aeb196b1d0d)

The `token` value is passed in as a GitHub Actions secret to enable the CI pipeline to run on the main repo, but the `token` value is undefined in forked repos. This causes contributors to have to run tests locally which is an unnecessary extra step to contributing.

**To Reproduce**
1. Make changes within forked repo
2. Open PR in main repo
3. Run CI pipeline

**Expected behavior**
The CI pipeline shouldn't fail due to a missing Firebase config object. Rather it should only fail when one of our automated tests fails.

**GitHub Actions**
 - OS: Linux

**Comment by PeaceOloruntoba** [comment] 2023-06-21 17:58
Based on the provided information, it appears that the issue is related to a missing token argument in the GitHub Actions workflow configuration. To resolve this, you can follow these steps:

Open your GitHub Actions workflow file in the main repository.
Locate the step or job where the --token argument is being used.
Ensure that the token value is being passed correctly from the GitHub Actions secret.
Update the workflow configuration to handle cases where the token value is not defined in forked repositories.
Here's an example of how you can modify the workflow configuration to handle the missing token argument:

yaml
Copy code
name: Your CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test --token ${{ secrets.YOUR_TOKEN_SECRET }} || echo "Tests failed"

      - name: Deploy to production
        if: github.repository == 'owner/main-repo'
        run: |
          # Add deployment steps for the main repository here
In the above example, the YOUR_TOKEN_SECRET represents the name of the GitHub Actions secret that contains the token value. By using the ${{ secrets.YOUR_TOKEN_SECRET }} syntax, the token value will be injected into the command as an argument. The || echo "Tests failed" part ensures that the CI pipeline does not fail solely due to the tests failing.

Additionally, the deployment step is conditional (if: github.repository == 'owner/main-repo') to ensure it only runs when changes are made in the main repository, not in forked repositories.

Make sure to adjust the workflow file according to your specific setup and requirements.

Once you've made the necessary changes, commit and push the updated workflow file to the main repository. The CI pipeline should now handle the missing token argument appropriately and only fail when the tests actually fail.

**Comment by PeaceOloruntoba** [comment] 2023-06-21 17:58
The example provided assumes a generic workflow structure and may require modifications to fit your specific use case.

To effectively troubleshoot and resolve the issue, consider the following steps:

Examine the existing GitHub Actions workflow file in your main repository and locate the step or job that references the --token argument.
Verify that the token value is being passed correctly from the GitHub Actions secret. You can check if the secret is properly defined in the repository's settings. Ensure that the secret name matches the one used in the workflow file.
Update the workflow configuration to handle cases where the token value is not defined in forked repositories. One approach is to conditionally check if the token is available before running the command.
Test the updated workflow by creating a new pull request from the forked repository to the main repository and observe the CI pipeline's behavior.

**Closed** 2023-06-21 19:14 UTC
Labels: bug, help wanted
