### ISSUE TITLE
Sticky navbar is not working on mobile version

### ISSUE THREAD

**Issue by bhantsi** [nkowaokwu/igbo_api#693] opened 2023-06-22 16:02 UTC
**Describe the bug**
The sticky navbar on mobile disappears as the user scrolls down to various website sections.
**To Reproduce**
1. Go to the homepage on mobile
2. Scroll down to any section
3. See bug

**Expected behavior**
The navbar should remain fixed at the top (or any other specified position) of the webpage as the user scrolls. This ensures that the navigation menu is always accessible, regardless of the user's position on the page.
Bear in mind that the sticky navbar should adapt to different screen sizes and devices. It should be responsive and adjust its layout and appearance accordingly, ensuring optimal usability on mobile devices as well as desktops

**Screenshots**
![1687449622617](https://github.com/nkowaokwu/igbo_api/assets/26586086/34409e80-21bd-4ec4-b95c-72f8c4446932)

**Comment by kingdanie** [comment] 2023-06-23 12:28
@ijemmao this is the intended behaviour for mobile devices? yes if assign it to me, let me handle it.

**Comment by ijemmao** [comment] 2023-06-24 14:08
@kingdanie go for it!

**Comment by ijemmao** [comment] 2024-06-14 23:13
Closing since this issue since it doesn't seem relevant anymore. Feel free to reopen. Thank you for opening this ticket!

**Closed by ijemmao** 2024-06-14 23:13 UTC
